#pragma once

// Request Types...
#define AGS_MSGTYPE_REGISTER			1
#define AGS_MSGTYPE_WRITETOSERVER		2
#define AGS_MSGTYPE_WRITEARRAYTOSERVER	3

// Data Typs...
#define AGS_DATATYPE_SINT8	1	// INT1
#define AGS_DATATYPE_UINT8	2	// LOG1
#define AGS_DATATYPE_SINT16	3	// INT2
#define AGS_DATATYPE_UINT16	4	// LOG2
#define AGS_DATATYPE_SINT32	5	// INT4
#define AGS_DATATYPE_UINT32	6	// LOG4
#define AGS_DATATYPE_REAL4	7	// REAL4
#define AGS_DATATYPE_REAL8	8	// REAL8